/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorycontrolgui;
import java.sql.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author Acer
 */
public class InvControl extends javax.swing.JFrame {

    /**
     * Creates new form InvControl
     */
    
    String [] storesLi;
    String [] itemLi;
    int [] thresholdLi;
    int [] quantityLi;
    
    public InvControl() {
        initComponents();
        
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
            "jdbc:mysql://localhost:3306/Inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            Statement st = (Statement) connection.createStatement();
            String prepare = "select*from stores;";
            ResultSet rs = st.executeQuery(prepare);
            
            int x = 0;
                    
            while(rs.next()){
                x++;
            }
            this.storesLi = new String[x];

            ResultSet qs = st.executeQuery("Select*from stores;");            
            while(qs.next()){
                String sts = qs.getString("storeID");
                storesLi[qs.getRow()-1] = sts;
            }
            
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(storesLi));
            
            
            
            
            
            
            
            
        try{
            String prepare2 = "select*from inventory where storeID = '" + (String) jComboBox1.getSelectedItem() + "';";
            ResultSet gs = st.executeQuery(prepare2);
            
            x = 0;
                    
            while(gs.next()){
                x++;
            }
            this.itemLi = new String[x];
            this.thresholdLi = new int[x];
            this.quantityLi = new int[x];

            ResultSet bs = st.executeQuery("select*from inventory where storeID = '" + (String) jComboBox1.getSelectedItem() + "';");            
            while(bs.next()){
                String ite = bs.getString("itemID");
                itemLi[bs.getRow()-1] = ite;
                int thres = bs.getInt("threshold");
                thresholdLi[bs.getRow()-1] = thres;
                int qty = bs.getInt("quantity");
                quantityLi[bs.getRow()-1] = qty;
            }
            
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(itemLi));
            int index = jComboBox2.getSelectedIndex();
            jTextField1.setText(String.valueOf(quantityLi[index]));
            jSpinner1.setValue((Integer) thresholdLi[index]);
        }catch(SQLException e){
            System.err.println(e);
        }
            
            
            
            
            
            
            
            
            
        }catch(SQLException e){
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Store ID");

        jLabel2.setText("Item ID");

        jLabel3.setText("Threshold");

        jLabel4.setText("Quantity");

        jLabel5.setText("Remove/Restock");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Restock");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(1, 1, 1)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new OwnerLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
            "jdbc:mysql://localhost:3306/Inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            Statement st = (Statement) connection.createStatement();
            PreparedStatement inst = connection.prepareStatement("update Inventory set threshold = ? where storeID = ? and itemID = ?;"); 
            inst.setInt(1, (Integer) jSpinner1.getValue());
            inst.setString(2, (String) jComboBox1.getSelectedItem());
            inst.setString(3, (String) jComboBox2.getSelectedItem());
            inst.executeUpdate();
            int index = jComboBox1.getSelectedIndex();
        }catch(Exception e){
            System.err.print(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int index = jComboBox2.getSelectedIndex();
        jTextField1.setText(String.valueOf(quantityLi[index]));
        jSpinner1.setValue((Integer) thresholdLi[index]);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
            "jdbc:mysql://localhost:3306/Inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            Statement st = (Statement) connection.createStatement();
            String prepare2 = "select*from inventory where storeID = '" + (String) jComboBox1.getSelectedItem() + "';";
            ResultSet gs = st.executeQuery(prepare2);
            
            int x = 0;
                    
            while(gs.next()){
                x++;
            }
            this.itemLi = new String[x];
            this.thresholdLi = new int[x];
            this.quantityLi = new int[x];

            ResultSet bs = st.executeQuery("select*from inventory where storeID = '" + (String) jComboBox1.getSelectedItem() + "';");            
            while(bs.next()){
                String ite = bs.getString("itemID");
                itemLi[bs.getRow()-1] = ite;
                int thres = bs.getInt("threshold");
                thresholdLi[bs.getRow()-1] = thres;
                int qty = bs.getInt("quantity");
                quantityLi[bs.getRow()-1] = qty;
            }
            
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(itemLi));
            int index = jComboBox2.getSelectedIndex();
            jTextField1.setText(String.valueOf(quantityLi[index]));
            jSpinner1.setValue((Integer) thresholdLi[index]);
        }catch(SQLException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = jComboBox2.getSelectedIndex();
        if(quantityLi[index] < (Integer) jSpinner2.getValue()){
            JOptionPane.showMessageDialog(null, "Cannot Remove more than in inventory");
        }else{
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
            "jdbc:mysql://localhost:3306/Inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            PreparedStatement inst = connection.prepareStatement(" insert into removes values(now(), ?,?,?);"); 
            inst.setString(1, (String) jComboBox1.getSelectedItem());
            inst.setString(2, (String) jComboBox2.getSelectedItem());
            inst.setInt(3, (Integer) jSpinner2.getValue());
            inst.executeUpdate();
            quantityLi[index] -= (Integer) jSpinner2.getValue();
            jTextField1.setText(String.valueOf(quantityLi[index]));
        }catch(Exception e){
            System.err.print(e);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
            "jdbc:mysql://localhost:3306/Inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            PreparedStatement inst = connection.prepareStatement(" insert into restocks values(now(), ?,?,?);"); 
            inst.setString(1, (String) jComboBox1.getSelectedItem());
            inst.setString(2, (String) jComboBox2.getSelectedItem());
            inst.setInt(3, (Integer) jSpinner2.getValue());
            inst.executeUpdate();
            int index = jComboBox2.getSelectedIndex();
            quantityLi[index] += (Integer) jSpinner2.getValue();
            jTextField1.setText(String.valueOf(quantityLi[index]));
        }catch(Exception e){
            System.err.print(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
