/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorycontrolgui;
import java.sql.*;
import java.util.*;
/**
 *
 * @author Acer
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    
    String [] redSID;
    String [] redIID;
    String [] redDate;
    
    String [] allSID;
    String [] allIID;
    String [] allDate1;
    String [] allDate2;
    String [] allStatus;
    
    public Reports() {
        initComponents();
        
        String USERNAME = "Blanc";
        String PASSWORD = "shiro";
        String url =
                "jdbc:mysql://localhost:3306/inventory";
        try{
            Connection connection = DriverManager.getConnection(url, USERNAME, PASSWORD);
            Statement st = (Statement) connection.createStatement();
            ResultSet rs = st.executeQuery("select*from reports where status = 'red';");
            
            int x=0;
            while(rs.next()){
                x++;
            }
            this.redSID = new String[x];
            this.redIID = new String[x];
            this.redDate = new String[x];
            
            rs.close();
            rs = st.executeQuery("select*from reports where status = 'red';");
            int index;
            while(rs.next()){
                index = rs.getRow()-1;
                redSID[index] = rs.getString("storeID");
                redIID[index] = rs.getString("itemID");
                redDate[index] = rs.getString("Date1");
            }
            rs.close();
            
            x = 0;
            rs = st.executeQuery("select*from reports;");
            while(rs.next()){
                x++;
            }
            this.allSID = new String[x];
            this.allIID = new String[x];
            this.allDate1 = new String[x];
            this.allDate2 = new String[x];
            this.allStatus = new String[x];
            rs.close();
            rs = st.executeQuery("select*from reports;");
            while(rs.next()){
                index = rs.getRow()-1;
                allSID[index] = rs.getString("storeID");
                allIID[index] = rs.getString("itemID");
                allDate1[index] = rs.getString("Date1");
                allDate2[index] = rs.getString("Date2");
                allStatus[index] = rs.getString("Status");
            }rs.close();
            
            
        }catch(Exception e){
            System.err.print(e);
        }
        jTextArea1.setText(format1());
        jTextArea2.setText(format2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("~~\nStore ID\t:\nItem ID\t:\nSince\t:\n~~\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("List of items that are under the threshold");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("~~\nStore ID\t:\nItem ID\t:\nDate1\t:\nDate2\t:\nStatus\t:\n~~");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("All reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new OwnerLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }
    
    
    private String format1(){
    String BT = "";
    String prep = "";
    String strID;
    String itemID;
    String date;
    
    for(int i = 0; i < this.redSID.length; i++){
        prep = "~~\n";
        strID = "Store ID\t:"+this.redSID[i];
        itemID = "Item ID\t:"+this.redIID[i];
        date = "Since\t:"+this.redDate[i];
        prep += strID;
        prep += "\n";
        prep += itemID;
        prep += "\n";
        prep += date;
        prep += "\n~~\n\n";
        BT +=prep;
    }
    return BT;
}
    private String format2(){
    String BT = "";
    String prep = "";
    String strID;
    String itemID;
    String date1;
    String date2;
    String stat;
    for(int i = 0; i < this.allSID.length; i++){
        prep = "~~\n";
        strID = "Store ID\t:"+this.allSID[i];
        itemID = "Item ID\t:"+this.allIID[i];
        date1 = "Date1\t:"+this.allDate1[i];
        date2 = "Date2\t:"+this.allDate2[i];
        stat = "Status\t:"+this.allStatus[i];
        prep += strID;
        prep += "\n";
        prep += itemID;
        prep += "\n";
        prep += date1;
        prep += "\n";
        prep += date2;
        prep += "\n";
        prep += stat;
        prep += "\n~~\n\n";
        BT +=prep;
    }
    return BT;
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}

